CREATE TABLE IF NOT EXISTS roles(
		role_id SERIAL PRIMARY KEY ,
		role_name VARCHAR(30) NOT NULL UNIQUE
);


INSERT INTO roles(role_name)
VALUES
('ADMIN'),
('RESIDENT'),
('PLUMBER'),
('ELECTRICIAN'),
('CARPENTER'),
('LIFT TECHNICIAN'),
('HOUSEKEEPING'),
('SECURITY');

